server:
  port: 8088
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 1234567890
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
mybatis:
  type-aliases-package: com.leyou.order.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ly:
  jwt:
    pubKeyPath: D:/heima/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1

