spring:
  application:
    name: page-service
    #关闭缓存，修改页面时不需要重启即可完成更改
  thymeleaf:
    cache: false
  mvc:
      static-path-pattern=/**
  rabbitmq:
    host: 192.168.209.129
    username: leyou
    password: leyou
    virtual-host: /leyou
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
